### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by fellowEngineer** [fellowEngineer/firebase_projects#20]
###  On README.md 
In **[Getting Started](https://github.com/fellowEngineer/firebase_projects)** section.
at **Step 9** : where the line says : "9. Run to following Commands to install required dependencies"

The given Command are like this : 

 1. \``` npm i \``` or \``` npm install ```
 2. \``` nodemon app.js \``` or \``` node app.js ``` starts the server up .

## You have to change it to (as given below)

``` 
npm install 
```
``` 
nodemon app.js 
``` 
starts the server up .

Please make sure to choose a relevant branch name, also describe the efforts you made to solve this issue.

**Comment by Rajdeep1311** [comment]
I changed it

**Comment by Rajdeep1311** [comment]
Please close my PR #21
